### ISSUE TITLE
significant performance issue

### ISSUE THREAD

**Issue by zamfofex** [zamfofex/dummyette#1]
Some time before I published the bot to this repository, I refactored it into multiple modules that can be used independently.

Some of such changes seem to have made it *really* slow to actually choose a move to make, though. Whereas before, it would be able to make a move in around two seconds or so, now, it takes around a full minute, which is a pretty significant difference.

I haven’t assessed the reason to be certain yet, but I’m very positive that it has to do with finding valid moves in the `chess.js` module, which was something that always took a significant portion of time.

**Comment by OverLordGoldDragon** [comment]
Please add.
