### ISSUE TITLE
Halfmove clock and Fullmove number miss in `toFEN` output

### ISSUE THREAD

**Issue by arthurchumak** [zamfofex/dummyette#6]
while exporting fen `Halfmove clock` and `Fullmove number` miss
```
const notation = await import('dummyette/notation.js');
chess = notation.fromFEN('rnbqkbnr/pppppppp/8/8/8/3PP1BN/PPP2PPP/RNBQ1K1R w KQkq - 0 1');
notation.toFEN(chess);
>>> 'rnbqkbnr/pppppppp/8/8/8/3PP1BN/PPP2PPP/RNBQ1K1R w KQkq -'
```

**Comment by zamfofex** [comment]
This is not currently supported, unfortunately. I don’t think I want to incorporate support for this into the `Board` API, but I do want to add support for it in a different part of the library.

**Comment by arthurchumak** [comment]
@zamfofex got it, thank for answers!
